### ISSUE TITLE
Build folder and Intermediate build folder are created and used inside the project folder

### ISSUE THREAD

**Issue by CamMouren** [AArnott/ReadOnlySourceTree#7]
Steps to repro:
-Zip the current repo
-Extract the "DefaultCSharpClassLibrary" folder
-Open it Under VS14.0.24720.0 CE using File->Open-Project/Solution
-Save a solution file under the parent folder "..\"
-Modify MSBuild project build output verbosity in VS to diagnostic
-Restore the "ReadOnlySourceTree" Nuget package updating it to the current latest (1.13)
-Clean the solution
-Build the solution
-Copy and paste MSBuild output to a log file (attached in for my system here... sorry but in french because I have not found a way to output it in english)
[MSBuildLog.txt](https://github.com/AArnott/ReadOnlySourceTree/files/67451/MSBuildLog.txt)

**Comment by AArnott** [comment]
Your steps don't adequately identify what the src folder is. Review the readme file for how to set up your project. If you alter your repro steps slightly to add a .reposrcroot file in the src folder that contains your solution, you should find that bin and obj folders are created just above that.
